config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root  'letters#index'
  resources :letters, only: [:new, :create]
  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/letter.rb
class Letter < ApplicationRecord

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :letters
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/letters_controller.rb
class LettersController < ApplicationController

  before_action :move_to_index, except: :index

  def index
    @letters = current_user.letters.last
    @friend_point = current_user.letters.count
  end

  def new
  end

  def create
    Letter.create(habit: letter_params[:habit], user_id: current_user.id)
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end


  private
  def letter_params
    params.permit(:habit)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @managements = current_user.letters.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/letters_helper.rb
module LettersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Lubbock
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .header
      .header__siteTitle
        %a{ href: 'http://localhost:3000/', id: 'top' }Lubbock
      .header__image 
      - if user_signed_in?
        .header__button
          = link_to "メェ〜ルする", new_letter_path, method: :get
          %i.fa.fa-envelope
        .header__button
          = link_to "マネージメェント", user_path(:id), method: :get
          %i.fa.fa-check-circle
        .header__button
          = link_to "ジョンのメェ〜言", destroy_user_session_path, method: :delete
          %i.fa.fa-comment
        .header__button
          = link_to "おやすみ", destroy_user_session_path, method: :delete
          %i.fa.fa-bed
        .header__message
          %p
          = current_user.name 
          おかえりなさい。
          %br
          今日はどんな一日だった？
          %br
          %br
          ジョンより
      -else
        .header__copy
          ー毎日、あなたを、受け入れるー

    = yield

app/views/letters/create.haml
投稿が完了しました。

app/views/letters/index.html.haml
%body
  .index__body
    .dayly__habit
      - if @letters.id >= 1
        %p
          = @letters.created_at
          %br
          = @letters.habit

    .jon__message
      - if @friend_point == 1
        %p
          →
          =current_user.name
          はじめまして！
          これから、よろしくね。
          ぼくの名前はジョンって言うんだ
      
      - if @friend_point >= 2 && @friend_point <= 4
        %p
          →
          =current_user.name 
          習慣を記録するのには慣れてきた？
          君が送ってくれるメールはいつも美味しいよ！ムシャムシャ
      
      -if @friend_point == 5
        %p
          →
          =current_user.name 
          5回目の記録おめでとう！

app/views/letters/new.haml
%body
  = form_tag('/letters', method: :post) do
    投稿する
    %br
    %input{:placeholder => "今日達成した習慣を入力してください", :type => "text", :name => "habit", :size => "40"}

app/views/users/show.haml
%body
  -@managements.each do |manage|
    = manage.created_at
    %br
    = manage.habit
    %br
    %br